### ISSUE TITLE
Errors building example

### ISSUE THREAD

**Issue by mt-caret** [timbertson/opam2nix-packages#13] opened 2018-02-20 05:12 UTC
I tried to build one of the examples, but I got an error while building opam2nix for one of the examples.
https://gist.github.com/mt-caret/bc90cf16ab29bec2a32b8e45854333b8

```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09.2973.e18442d4662 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.12pre5873_b76e282d`
 - channels(root): `"nixos-17.09.2973.e18442d4662"`
 - channels(delta): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

**Comment by timbertson** [comment] 2018-06-26 11:21
Duplicate of #7

**Closed by timbertson** 2018-06-26 11:21 UTC
